import { Inter } from 'next/font/google'
import './globals.css'
import { Marcellus } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
const marcellus = Marcellus({
  subsets:['latin'],
  weight:'400'
})
export const metadata = {
  title: 'MateuszWebSite',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/photo/favicon.png" />
      </head>
      <body className={marcellus.className}>
              {children}
      </body>
    </html>
  )
}
